treino_mvc2/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using treino_mvc2.Data;
using treino_mvc2.Models;

namespace treino_mvc2.Controllers
{
    [Authorize]
    public class AnimalController : Controller
    {
        private readonly ApplicationDbContext database;
        public AnimalController(ApplicationDbContext database)
        {
            this.database = database;
        }

        public IActionResult Listar() //listar os animais
        {
            var animais = database.Animal.ToList();
            return View(animais);
        }

        [Authorize(Policy = "TipoUser")] //so acessa quem for doar
         //so acessa quem for veterinario
        public IActionResult Cadastrar() //formulario
        {
            return View();
        }

        [Authorize(Policy = "TipoVet")] //so veterinario acessa
        public IActionResult ListarEditar() //listar os animais
        {
            var animais = database.Animal.ToList();
            return View(animais);
        }

        [Authorize(Policy = "TipoVet")]
        public IActionResult Editar(int id)
        {
            Animais animais = database.Animal.First(registro => registro.Id == id);
            return View("Cadastrar", animais); //usando o mesmo formulario cadastrar
        }

        [Authorize(Policy = "TipoVet")]
        public IActionResult Deletar(int id)
        {
            Animais animais = database.Animal.First(registro => registro.Id == id); 
            database.Animal.Remove(animais);
            database.SaveChanges(); 
            return RedirectToAction("Listar"); //deleta um animal
        }

        [HttpPost] //essa action esta sendo acessada pelo formulario de cadastrar animal
        public IActionResult Salvar(Animais animais) 
        {
            //salvando as informacoes no BD na tabela animal
            if(animais.Id == 0)
            {
                //salve um novo animal
                database.Animal.Add(animais);
            }
            else
            {
                //atualizar um animal
                Animais animalDoBanco = database.Animal.First(registro => registro.Id == animais.Id);
                
                animalDoBanco.Nome = animais.Nome;
                animalDoBanco.Raca = animais.Raca;
                animalDoBanco.Idade = animais.Idade;
                animalDoBanco.Telefone = animais.Telefone;
                animalDoBanco.Comentario = animais.Comentario;
            }
            
            
            database.SaveChanges();
            
            return RedirectToAction("Listar");
        }

       
    }
}

treino_mvc2/Views/Animal/Cadastrar.cshtml
@model treino_mvc2.Models.Animais

<div>
    <div class="text-center"> 
        
        <img src="~/img/cadastre.png" alt="Banner Adote Amor" width="100%">
        <br>
        <h2>Cadastro de Animais</h2>
        <hr>
        <form class="form-horizontal" asp-controller="Animal" asp-action="Salvar" method="POST">
            <input type="hidden" asp-for="Id">
            <input type="text" class="form-control" asp-for="Nome" placeholder="Nome"> <br/>
            <input type="text" class="form-control" asp-for="Raca" placeholder="Raca"> <br/>
            <input type="number" class="form-control" asp-for="Idade" placeholder="Idade"> <br/>
            <input type="text" class="form-control" asp-for="Telefone" placeholder="Telefone"> <br/>
            <input type="text" class="form-control" asp-for="Comentario" placeholder="Comentario"> <br/>
            <button class="btn btn-outline-warning">Cadastrar</button>
        </form>
        
    </div>
</div>

treino_mvc2/Views/Animal/Listar.cshtml
@model IEnumerable<treino_mvc2.Models.Animais>  //tipo do objeto Model

<div class="container-sm">
<img src="~/img/adotar.png" alt="Banner de doacao" width="100%">
<br/>
<br/>
    <h2> Todos os animais para adoção</h2>
    <hr/>

    <div class="row">
        <div class="col-sm-6">
            <a href="/Animal/Cadastrar" class="btn btn-warning btn-block">Novo animal</a>
        </div>
        <div class="col-sm-6">
            <a href="/Animal/ListarEditar" class="btn btn-dark btn-block">Sou Veterinario</a>
        </div>
    </div>

<hr>

<div class="row">
@foreach (var animais in Model) // @model
{
<div class="col-sm-4">
    <div class="card" style="width: 22rem;">
        <img src="~/img/gatodesenho.jpg" class="card-img-top" alt="animal">
        <div class="card-body">
            <h5 class="card-title">@animais.Nome</h5>
            
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Raca: @animais.Raca</li>
            <li class="list-group-item">Idade: @animais.Idade</li>
            <li class="list-group-item">Telefone: @animais.Telefone</li>
        </ul>
        <div class="card-body">
           
            <p class="card-text">Comentario: @animais.Comentario</p>
        </div>
    </div>
    <br/>
</div>
}
</div>
</div>

treino_mvc2/Views/Animal/ListarEditar.cshtml
@model IEnumerable<treino_mvc2.Models.Animais>  //tipo do objeto Model animal

<h2>Todos os animais para adoção</h2>
<a href="/Animal/Cadastrar" class="btn btn-warning">Novo animal</a>
<hr>
@foreach (var animais in Model) // @model
{
    <p>Nome: @animais.Nome</p>
    <p>Raca: @animais.Raca</p>
    <p>Idade: @animais.Idade</p>
    <p>Telefone: @animais.Telefone</p>
    <p>Comentario: @animais.Comentario</p>
    <a href="/Animal/Editar/@animais.Id" class="btn btn-success">Editar</a>
    <a href="/Animal/Deletar/@animais.Id" class="btn btn-danger">Deletar</a>
    <hr>
}